<a href="https://colab.research.google.com/github/SebastianCastilloDev/curso-numpy/blob/main/numpy_basico_clase6_yacklyon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
m = np.arange(24).reshape(4,6)
print(m [3,4])
print(m)

m1 = np.array([2,5,6,78,8,5,4,3])
print(np.sort(m1))

m1 = np.array([2,3])
print(np.power(m1,3)) #elevar cada elemento al cubo

print(np.array(m1**2))

m1 = np.array([2,3,4,5,6,7])
print(np.array(m1>=4))

22
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 2  3  4  5  5  6  8 78]
[ 8 27]
[4 9]
[False False  True  True  True  True]
