<a href="https://colab.research.google.com/github/SebastianCastilloDev/curso-numpy/blob/main/numpy_basico_clase5_yacklyon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
m = np.arange(27).reshape(3,3,3)
print(m.size)
print(m)

27
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
